### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by bw-matthew** [rra/c-tap-harness#3]
The readme features the following build instructions:

> You can build C TAP Harness and run its internal test suite with:

>      ./configure
>      make
>      make check

This does not work because there is no configure file in the project. If I use the build steps of:

```
autoreconf -vif
./configure
make
```

Then the build fails with the following error message:

> make: *** No rule to make target \`docs/api/bail.3', needed by `all-am'. Stop.

I have forked this project and added a dockerfile which demonstrates this issue. You can find that [here](https://github.com/bw-matthew/c-tap-harness). Building the docker image will fail and the error will be displayed.

**Comment by rra** [comment]
Run `./autogen` from a fresh Git clone to get all the supporting files.  You will need current versions of Autoconf and Automake.

The README was written for people who are downloading the tarballs from http://www.eyrie.org/~eagle/software/c-tap-harness/ as that's the "normal" distribution mechanism.  The Github thing is a fairly new experiment on my part.  I'll try to figure out how to document this better for people cloning directly from Github.  Apologies for that; this project is rather old-school and predates Github (and Git).

**Comment by bw-matthew** [comment]
I can confirm that this works. Thank you very much for the speedy response.
