### ISSUE TITLE
Install fails because of preexisting man pages

### ISSUE THREAD

**Issue by vonbrand** [rra/c-tap-harness#9]
release/4.7-8-ge169247

`make install` fails complaining that some manpage is already present when linking the file (older version installed). A fix is to add `-f` to  `ln`'s flags in the Makefile:

```
--- Makefile~	2022-02-04 00:23:25.915145798 -0300
+++ Makefile	2022-02-04 00:24:12.997853946 -0300
@@ -468,7 +468,7 @@
 LDFLAGS = 
 LIBOBJS = 
 LIBS = 
-LN_S = ln -s
+LN_S = ln -sf
 LTLIBOBJS = 
 MAINT = #
 MAKEINFO = ${SHELL} /home/vonbrand/tmp/c-tap-harness/build-aux/missing makeinfo
```

Sorry, no real understanding of the `autoconf` mess to know how to really fix this.

**Comment by rra** [comment]
Thank you! Looks like bstrndup was missing its `rm` to handle previous installs.
